server:
  port: 1201
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heySeattleW/cloud-demo.git
          search-paths: /config-server/src/main/java/com/hey/config
          username: 354034910@qq.com
          password: l1141180
