spring:
  application:
    name: hystrix-turbine
server:
  port: 8989
management:
  port: 8990
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
turbine:
  app-config: eureka-consumer-feign,eureka-client
  combine-host-port: true